import Column from "../Column"
import Row from "../Row"
import KeyboardLetter from "./KeyboardLetter"

const Keyboard = ({
    addLetter,
    removeLetter,
    submit,
}) => {
    return (
        <Column
            width='100%'
        >
            <Row>
                <KeyboardLetter 
                    letter='q'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='w'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='e'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='r'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='t'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='y'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='u'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='i'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='o'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='p'
                    onClick={addLetter}
                />
            </Row>
            <Row>
                <KeyboardLetter 
                    letter='a'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='s'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='d'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='f'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='g'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='h'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='j'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='k'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='l'
                    onClick={addLetter}
                />
            </Row>
            <Row>
                <KeyboardLetter 
                    letter='z'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='x'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='c'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='v'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='b'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='n'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='m'
                    onClick={addLetter}
                />
                <KeyboardLetter 
                    letter='p'
                    onClick={addLetter}
                />
            </Row>
            <Row>
                <KeyboardLetter 
                    letter='Back'
                    onClick={removeLetter}
                />
                <KeyboardLetter 
                    letter='Enter'
                    onClick={submit}
                />
            </Row>
        </Column>
    )
}

export default Keyboard